# This workflow gets triggered manually

name: Deploy CloudTalents App Infrastructure to AWS

on:
  workflow_dispatch: # manual trigger
    inputs:
        version:
            description: 'AMI version to use'
            required: true
            type: string

env:
  AWS_REGION: us-east-1 # set this to your preferred AWS region, e.g. us-west-1
  AWS_ACCOUNT: 879381279300 # set this to your account number
  CDK_ROLE_NAME: GitHubCdkRole # set this to your IAM Role name
  gitubRef: ${{github.ref}}
  version: ${{inputs.version}}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  infra:
    name: CDK
    runs-on: ubuntu-latest

    # version and instance id are stored as output and will be passed to the next job
    outputs:
      version: ${{steps.cdk_out.outputs.version}}
      instance_id: ${{steps.cdk_out.outputs.instance}}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT}}:role/${{env.CDK_ROLE_NAME}}
          role-session-name: github-session-cdk

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install AWS CDK
        run: |
          cd cdk
          npm i -g aws-cdk
          npm install

      - name: Synth stack
        run: |
          cd cdk
          cdk synth CloudTalentsAppStack

      # - name: Diff stack
      #   run: |
      #     cd cdk
      #     cdk diff CloudTalentsAppStack

      - name: Deploy stack
        run: |
          cd cdk
          cdk deploy CloudTalentsAppStack --require-approval never

      - name: Outputs
        id: cdk_out
        run: |
          echo "version=$(aws cloudformation describe-stacks --stack-name CloudTalentsAppStack --query "Stacks[0].Outputs[?OutputKey=='Version'].OutputValue" --output text)" >> "$GITHUB_OUTPUT"
          echo "instance=$(aws cloudformation describe-stacks --stack-name CloudTalentsAppStack --query "Stacks[0].Outputs[?OutputKey=='InstanceId'].OutputValue" --output text)" >> "$GITHUB_OUTPUT"
